apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - ssh:
      address: 192.168.64.14
      user: ubuntu
      keyPath: ~/.ssh/id_rsa
    role: controller
  - ssh:
      address: 192.168.64.15
      user: ubuntu
      keyPath: ~/.ssh/id_rsa
    role: worker
  - ssh:
      address: 192.168.64.16
      user: ubuntu
      keyPath: ~/.ssh/id_rsa
    role: worker
